language: swift
osx_image: xcode10
script: make ci
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - make lint
  - carthage bootstrap
notifications:
  irc: "chat.freenode.net#thepotionlab-notifications"

